### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by ojsimon** [EsteveSegura/insta-growth#1]
Hi, 

I cannot seem to get it to work. When I click either graphical or list view it says it will start in a few minutes but I leave it and nothing loads. 

On terminal I get the error 

`(node:5938) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)`

Any suggestions?

**Comment by EsteveSegura** [comment]
Sorry for delay in answer. You can make the project again, now its working.... some internal problems with dependencies!
